# Generated by Django 3.1.5 on 2021-03-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('season', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Сезон')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата конца')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.CharField(max_length=500, verbose_name='Видео')),
                ('marathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Рост')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('girth_breast', models.FloatField(verbose_name='Обхват груди')),
                ('girth_waist', models.FloatField(verbose_name='Обхват талии')),
                ('girth_hips', models.FloatField(verbose_name='Обхват бёдер')),
                ('girth_shoulders', models.FloatField(verbose_name='Обхват плеч')),
                ('girth_arm', models.FloatField(verbose_name='Обхват руки')),
                ('girth_leg', models.FloatField(verbose_name='Обхват ноги')),
                ('date', models.DateField(verbose_name='Дата замеров')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.client', verbose_name='Клиент')),
                ('marathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон')),
            ],
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.CharField(max_length=500, verbose_name='Видео')),
                ('marathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(null=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.client', verbose_name='Клиент')),
                ('marathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон')),
            ],
        ),
    ]
