# Generated by Django 3.1.5 on 2021-03-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='site_image', verbose_name='Изображение'),
        ),
    ]
