# Generated by Django 3.1.5 on 2021-01-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
    ]
