# Generated by Django 3.1.5 on 2021-01-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210105_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.DecimalField(decimal_places=0, default=111, max_digits=10, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
