# Generated by Django 3.1.5 on 2021-03-23 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_parameter_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='client',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
