# Generated by Django 3.1.5 on 2021-02-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_client_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Рост')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('girth_breast', models.FloatField(verbose_name='Обхват груди')),
                ('girth_waist', models.FloatField(verbose_name='Обхват талии')),
                ('girth_hips', models.FloatField(verbose_name='Обхват бёдер')),
                ('girth_shoulders', models.FloatField(verbose_name='Обхват плеч')),
                ('girth_arm', models.FloatField(verbose_name='Обхват руки')),
                ('girth_leg', models.FloatField(verbose_name='Обхват ноги')),
                ('date', models.DateField(verbose_name='Дата замеров')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.DecimalField(decimal_places=0, default=111, max_digits=10, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.client', verbose_name='Клиент'),
        ),
    ]
