# Generated by Django 3.1.5 on 2021-03-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='no_image.jpg', upload_to='photos/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
