# Generated by Django 3.1.5 on 2021-03-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210327_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='site_image', verbose_name='Изображение'),
        ),
    ]
