# Generated by Django 3.1.5 on 2021-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210327_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='static', verbose_name='Изображение'),
        ),
    ]
