# Generated by Django 3.1.5 on 2021-05-13 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210327_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='description',
        ),
        migrations.AddField(
            model_name='diary',
            name='breakfast',
            field=models.TextField(null=True, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='diary',
            name='dinner',
            field=models.TextField(null=True, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='diary',
            name='lunch',
            field=models.TextField(null=True, verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='diary',
            name='snack',
            field=models.TextField(null=True, verbose_name='Перекус'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='marathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон'),
            preserve_default=False,
        ),
    ]
