# Generated by Django 3.1.5 on 2021-01-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_marathon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.client', verbose_name='Клиент')),
                ('marathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон')),
            ],
        ),
    ]
