# Generated by Django 3.1.5 on 2021-03-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_parameter_marathon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.CharField(max_length=500, verbose_name='Видео')),
                ('marathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.marathon', verbose_name='Марафон')),
            ],
        ),
    ]
